spring:
  application:
    name: strikeraz

  datasource:
    url: jdbc:postgresql://localhost:5432/strikerazdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: sb22022202@gmail.com
    password: salambaku2202
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: strikerazSecretKey2024VeryLongSecretKeyForSecurityPurposes
  expiration: 86400000

server:
  port: 8080
  error:
    include-message: always